// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InfoHistory struct {
	ID             int32            `db:"id"`
	OsVersion      string           `db:"os_version"`
	OsQueryVersion string           `db:"os_query_version"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
}

type SystemSnapshot struct {
	ID            int32            `db:"id"`
	SnapshotTime  pgtype.Timestamp `db:"snapshot_time"`
	InstalledApps []string         `db:"installed_apps"`
}
