// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
)

type Querier interface {
	GetLatestAppsSnapshot(ctx context.Context) (SystemSnapshot, error)
	GetLatestOSInfo(ctx context.Context) (InfoHistory, error)
	InsertAppsSnapshot(ctx context.Context, installedApps []string) (SystemSnapshot, error)
	InsertOSSnapshot(ctx context.Context, arg InsertOSSnapshotParams) (InfoHistory, error)
}

var _ Querier = (*Queries)(nil)
